# Use root/example as user/password credentials
version: '3.8'

services:

       postgres:
              image: postgres
              restart: always
              ports:
                     - 5432:5432
              environment:
                     POSTGRES_USER: postgres
                     POSTGRES_PASSWORD: root@root
                     POSTGRES_DB: messageriedb
