spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/messageriedb
    username: postgres
    password: root@root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

#      en production, on doit utiliser un outils de migration de base de donn?e comme Liquibase ou Flyway



# docker run -d -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=root@root -e POSTGRES_DB=messageriedb -p 5432:5432 postgres:13



